import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./_providers/auth";
import Footer from "./_components/Footer";
import { Toaster } from "./_components/ui/sonner";
import Header from "./_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Restaurant Botticelli",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-stone-50`}>
				<AuthProvider>
					<Header />
					{children}
					<Toaster />
					<Footer />
				</AuthProvider>
			</body>
		</html>
	);
}
